# Generated by Django 5.2 on 2025-08-04 11:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("cotton", "Cotton"),
                            ("silk", "Silk"),
                            ("wool", "Wool"),
                            ("polyester", "Polyester"),
                            ("linen", "Linen"),
                            ("rayon", "Rayon"),
                            ("chiffon", "Chiffon"),
                            ("georgette", "Georgette"),
                            ("crepe", "Crepe"),
                            ("denim", "Denim"),
                            ("lycra", "Lycra"),
                            ("net", "Net"),
                            ("satin", "Satin"),
                            ("velvet", "Velvet"),
                            ("khadi", "Khadi"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "gsm",
                    models.PositiveIntegerField(
                        help_text="GSM (Grams per Square Meter)"
                    ),
                ),
                ("width", models.CharField(help_text="Width in inches", max_length=50)),
                (
                    "colors_available",
                    models.TextField(
                        help_text="Comma-separated list of available colors"
                    ),
                ),
                ("primary_color", models.CharField(max_length=50)),
                (
                    "usage",
                    models.CharField(
                        choices=[
                            ("shirt", "Shirt"),
                            ("trouser", "Trouser"),
                            ("suit", "Suit"),
                            ("dress", "Dress"),
                            ("curtain", "Curtain"),
                            ("bedsheet", "Bed Sheet"),
                            ("saree", "Saree"),
                            ("salwar", "Salwar Suit"),
                            ("lehenga", "Lehenga"),
                            ("ethnic_wear", "Ethnic Wear"),
                            ("casual_wear", "Casual Wear"),
                            ("formal_wear", "Formal Wear"),
                            ("home_decor", "Home Decor"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("care_instructions", models.TextField(blank=True)),
                (
                    "price_per_meter",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "wholesale_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wholesale price for bulk orders",
                        max_digits=10,
                    ),
                ),
                (
                    "minimum_order_quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="Minimum quantity in meters"
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(default=0, help_text="Stock in meters"),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new", "New"),
                            ("hot", "Hot"),
                            ("sale", "Sale"),
                            ("premium", "Premium"),
                            ("bestseller", "Best Seller"),
                        ],
                        max_length=50,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="products/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_email", models.EmailField(max_length=254)),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ]
                    ),
                ),
                ("review_text", models.TextField()),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_available"],
                name="products_pr_categor_c898cc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["material", "gsm"], name="products_pr_materia_dd0f30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["price_per_meter"], name="products_pr_price_p_7cab0e_idx"
            ),
        ),
    ]
